apiVersion: apps/v1
kind: Deployment
metadata:
  name: admindm
  labels:
    app: admindm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admindm
  template:
    metadata:
      labels:
        app: admindm
    spec:
      containers:
        - name: admindm
          image: "username/admindm:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
