name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./작가 관리/pom.xml
          mvn clean package -f ./ai service/pom.xml
          mvn clean package -f ./포인트 관리/pom.xml
          mvn clean package -f ./구독자관리/pom.xml
          mvn clean package -f ./서재플랫폼/pom.xml
          mvn clean package -f ./집필관리/pom.xml

      - name: Docker Build and push for 작가관리
        uses: docker/build-push-action@v4
        with:
          context: ./작가 관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/작가-관리:latest
            ghcr.io/${{ github.repository }}/작가-관리:${{ github.ref_name }}
            
      - name: Docker Build and push for AiService
        uses: docker/build-push-action@v4
        with:
          context: ./ai service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ai-service:latest
            ghcr.io/${{ github.repository }}/ai-service:${{ github.ref_name }}
            
      - name: Docker Build and push for 포인트관리
        uses: docker/build-push-action@v4
        with:
          context: ./포인트 관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/포인트-관리:latest
            ghcr.io/${{ github.repository }}/포인트-관리:${{ github.ref_name }}
            
      - name: Docker Build and push for 구독자관리
        uses: docker/build-push-action@v4
        with:
          context: ./구독자관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/구독자관리:latest
            ghcr.io/${{ github.repository }}/구독자관리:${{ github.ref_name }}
            
      - name: Docker Build and push for 서재플랫폼
        uses: docker/build-push-action@v4
        with:
          context: ./서재플랫폼
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/서재플랫폼:latest
            ghcr.io/${{ github.repository }}/서재플랫폼:${{ github.ref_name }}
            
      - name: Docker Build and push for 집필관리
        uses: docker/build-push-action@v4
        with:
          context: ./집필관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/집필관리:latest
            ghcr.io/${{ github.repository }}/집필관리:${{ github.ref_name }}
            
