name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./authordm/pom.xml
          mvn clean package -f ./aiservice/pom.xml
          mvn clean package -f ./pointdm/pom.xml
          mvn clean package -f ./userdm/pom.xml
          mvn clean package -f ./admindm/pom.xml
          mvn clean package -f ./authordm/pom.xml

      - name: Docker Build and push for Authordm
        uses: docker/build-push-action@v4
        with:
          context: ./authordm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/authordm:latest
            ghcr.io/${{ github.repository }}/authordm:${{ github.ref_name }}
            
      - name: Docker Build and push for Aiservice
        uses: docker/build-push-action@v4
        with:
          context: ./aiservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/aiservice:latest
            ghcr.io/${{ github.repository }}/aiservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Pointdm
        uses: docker/build-push-action@v4
        with:
          context: ./pointdm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pointdm:latest
            ghcr.io/${{ github.repository }}/pointdm:${{ github.ref_name }}
            
      - name: Docker Build and push for Userdm
        uses: docker/build-push-action@v4
        with:
          context: ./userdm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/userdm:latest
            ghcr.io/${{ github.repository }}/userdm:${{ github.ref_name }}
            
      - name: Docker Build and push for Admindm
        uses: docker/build-push-action@v4
        with:
          context: ./admindm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/admindm:latest
            ghcr.io/${{ github.repository }}/admindm:${{ github.ref_name }}
            
      - name: Docker Build and push for Authordm
        uses: docker/build-push-action@v4
        with:
          context: ./authordm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/authordm:latest
            ghcr.io/${{ github.repository }}/authordm:${{ github.ref_name }}
            
