server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: authordm
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**, /authorBookLists/**
        - id: aiservice
          uri: http://localhost:8083
          predicates:
            - Path=/publishings/**, 
        - id: pointdm
          uri: http://localhost:8084
          predicates:
            - Path=/points/**, /userSubscribedBookLists/**
        - id: userdm
          uri: http://localhost:8085
          predicates:
            - Path=/users/**, /userWishlists/**, /userReviews/**
        - id: admindm
          uri: http://localhost:8086
          predicates:
            - Path=/admins/**, /authorPublishBooklists/**, /userSubscribedBookLists/**
        - id: authordm
          uri: http://localhost:8087
          predicates:
            - Path=/authors/**, /manuscriptLists/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: authordm
          uri: http://authordm:8080
          predicates:
            - Path=/authors/**, 
        - id: aiservice
          uri: http://aiservice:8080
          predicates:
            - Path=/publishings/**, 
        - id: pointdm
          uri: http://pointdm:8080
          predicates:
            - Path=/points/**, 
        - id: userdm
          uri: http://userdm:8080
          predicates:
            - Path=/users/**, 
        - id: admindm
          uri: http://admindm:8080
          predicates:
            - Path=/admins/**, 
        - id: authordm
          uri: http://authordm:8080
          predicates:
            - Path=/authors/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
