---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authordm
  labels:
    app: authordm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authordm
  template:
    metadata:
      labels:
        app: authordm
    spec:
      containers:
        - name: authordm
          image: username/authordm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiservice
  labels:
    app: aiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiservice
  template:
    metadata:
      labels:
        app: aiservice
    spec:
      containers:
        - name: aiservice
          image: username/aiservice:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointdm
  labels:
    app: pointdm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointdm
  template:
    metadata:
      labels:
        app: pointdm
    spec:
      containers:
        - name: pointdm
          image: username/pointdm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdm
  labels:
    app: userdm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdm
  template:
    metadata:
      labels:
        app: userdm
    spec:
      containers:
        - name: userdm
          image: username/userdm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admindm
  labels:
    app: admindm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admindm
  template:
    metadata:
      labels:
        app: admindm
    spec:
      containers:
        - name: admindm
          image: username/admindm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authordm
  labels:
    app: authordm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authordm
  template:
    metadata:
      labels:
        app: authordm
    spec:
      containers:
        - name: authordm
          image: username/authordm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: authordm
  labels:
    app: authordm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: authordm


---


apiVersion: v1
kind: Service
metadata:
  name: aiservice
  labels:
    app: aiservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aiservice


---


apiVersion: v1
kind: Service
metadata:
  name: pointdm
  labels:
    app: pointdm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pointdm


---


apiVersion: v1
kind: Service
metadata:
  name: userdm
  labels:
    app: userdm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: userdm


---


apiVersion: v1
kind: Service
metadata:
  name: admindm
  labels:
    app: admindm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: admindm


---


apiVersion: v1
kind: Service
metadata:
  name: authordm
  labels:
    app: authordm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: authordm

