---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 작가 관리
  labels:
    app: 작가 관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 작가 관리
  template:
    metadata:
      labels:
        app: 작가 관리
    spec:
      containers:
        - name: 작가 관리
          image: username/작가 관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai service
  labels:
    app: ai service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai service
  template:
    metadata:
      labels:
        app: ai service
    spec:
      containers:
        - name: ai service
          image: username/ai service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 포인트 관리
  labels:
    app: 포인트 관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 포인트 관리
  template:
    metadata:
      labels:
        app: 포인트 관리
    spec:
      containers:
        - name: 포인트 관리
          image: username/포인트 관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 구독자관리
  labels:
    app: 구독자관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 구독자관리
  template:
    metadata:
      labels:
        app: 구독자관리
    spec:
      containers:
        - name: 구독자관리
          image: username/구독자관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 서재플랫폼
  labels:
    app: 서재플랫폼
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 서재플랫폼
  template:
    metadata:
      labels:
        app: 서재플랫폼
    spec:
      containers:
        - name: 서재플랫폼
          image: username/서재플랫폼:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 집필관리
  labels:
    app: 집필관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 집필관리
  template:
    metadata:
      labels:
        app: 집필관리
    spec:
      containers:
        - name: 집필관리
          image: username/집필관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: 작가 관리
  labels:
    app: 작가 관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 작가 관리


---


apiVersion: v1
kind: Service
metadata:
  name: ai service
  labels:
    app: ai service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ai service


---


apiVersion: v1
kind: Service
metadata:
  name: 포인트 관리
  labels:
    app: 포인트 관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 포인트 관리


---


apiVersion: v1
kind: Service
metadata:
  name: 구독자관리
  labels:
    app: 구독자관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 구독자관리


---


apiVersion: v1
kind: Service
metadata:
  name: 서재플랫폼
  labels:
    app: 서재플랫폼
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 서재플랫폼


---


apiVersion: v1
kind: Service
metadata:
  name: 집필관리
  labels:
    app: 집필관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 집필관리

