apiVersion: apps/v1
kind: Deployment
metadata:
  name: 작가 관리
  labels:
    app: 작가 관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 작가 관리
  template:
    metadata:
      labels:
        app: 작가 관리
    spec:
      containers:
        - name: 작가 관리
          image: "username/작가 관리:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
