apiVersion: apps/v1
kind: Deployment
metadata:
  name: authordm
  labels:
    app: authordm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authordm
  template:
    metadata:
      labels:
        app: authordm
    spec:
      containers:
        - name: authordm
          image: "username/authordm:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
