apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdm
  labels:
    app: userdm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdm
  template:
    metadata:
      labels:
        app: userdm
    spec:
      containers:
        - name: userdm
          image: "username/userdm:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
